# Generated by Django 3.1.2 on 2020-12-17 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bird',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('kingdom', models.CharField(max_length=50)),
                ('phylum', models.CharField(max_length=50)),
                ('classrank', models.CharField(max_length=50)),
                ('order', models.CharField(max_length=50)),
                ('family', models.CharField(max_length=50)),
                ('genus', models.CharField(max_length=50)),
                ('species', models.CharField(max_length=50)),
            ],
        ),
    ]
